= Building block

Building blocks (BBs) are software modules that can be deployed and combined in a standardized manner. Each building block is capable of working independently, but they can be combined to do much more. Read the https://govstack.gitbook.io/specification/architecture-and-nonfunctional-requirements/introduction#2.3-building-blocks[full definition in the GovStack Specifications].

== What do we use to build it?

The Building Block Software are build based on various different software stacks. Please visit the respective documentations for more insights.

Building Block Software has been selected through a public tender procedure. Each software is one possible solution to fulfilling the Building Block Specifications. The selection is no recommendation.

For our Building Block Emulators, visit our [sub page on emulators](emulators.md).

=== Building Block Software in Progress

|===
|BB Implementation  |BB Specification Compliance |Status

|Platform of Registries
|Registry Specification 1.0
|Planned

|===

== Which conceptual decisions do we follow?

The Building Block Implementations listed here have been openly procured by GovStack Initiative based on the GovStack Specifications. The providers of these BB implementations have been assigned to adapt/extend their offered software solutions to fully meet the GovStack Specifications for the respective Building Block.