= OpenIMIS

This repository is part of the https://github.com/GovStackWorkingGroup/sandbox[GovStack Sandbox]
and an implementation of the https://github.com/GovStackWorkingGroup/bb-registration[Registration Building Block Specifications].

The official [documentation](https://github.com/openimis) of the candidate.

Minimum set of components for [Sandbox](https://github.com/GovStackWorkingGroup/sandbox) is:

* Database
* Backend

== Database

https://github.com/openimis/database_postgresql

Backend expects database with predefine schema and data.

Custom https://github.com/openimis/database_postgresql/blob/main/Dockerfile[Dockerfile] provides necessary DB.

== Backend

https://github.com/openimis/openimis-be_py.git
Main repository:  https://github.com/openimis/openimis-be_py

Use dedicated https://github.com/openimis/openimis-be_py/tree/govstack-testing-setup[govstack-testing-setup] branch.

=== API

* https://en.wikipedia.org/wiki/Fast_Healthcare_Interoperability_Resources[FHIR] standard
* Swagger API https://dev-mssql.s1.openimis.org/api/api_fhir_r4/docs/swagger/[documentation]


== Adapter

GitHub https://github.com/openimis/openimis-be-govstack_api_py[repository].

https://govstack-global.atlassian.net/l/ce/uc1Eda2m[Documentation] for the Configurable "Registry" Django Model in openIMIS.

https://govstack-global.atlassian.net/wiki/spaces/GH/pages/172818480/Compliance+Evaluation+openIMIS[Compliance Evaluation: openIMIS]


https://govstack-global.atlassian.net/wiki/spaces/GH/pages/172818480/Compliance+Evaluation+openIMIS#Functional-Requirements-Digital-Registries[Case study - openIMIS]


== Sandbox deployment

1. Create DB docker image and deploy it.
2. Create a https://github.com/openimis/openimis-be_py/blob/develop/Dockerfile[docker image] of backend and [deploy](../charts) it.
3. Execute next commands in the backend pod:
* run migrations `python manage.py migrate`
* `python manage.py createsuperuser`  admin
* `python manage.py changepassword admin` govstack
4. Connect to DB and run https://github.com/GovStackWorkingGroup/sandbox-usecase-usct-backend/blob/main/docs/packages.md#sql-script[USCT migration].

== Useful commands

[,bash]
----
helm upgrade --install temprapid ./open-imis/ --create-namespace --namespace temprapid
----

[,bash]
----
helm install temprapid ./open-imis/ --create-namespace --namespace temprapid
----

[,bash]
----
helm uninstall temprapid --namespace temprapid
----

[,bash]
----
kubectl delete namespace temprapid
----
